# Generated by Django 4.0.5 on 2022-06-04 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('about', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='procedure/', verbose_name='Картинка')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('time', models.PositiveSmallIntegerField(help_text='Время в минутах', verbose_name='Длительность')),
                ('sorting', models.SmallIntegerField(blank=True, verbose_name='Номер сортировки')),
                ('unpublished', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Тэг')),
                ('url', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='ProcedureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='procedure_shots/', verbose_name='Изображение')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.procedure', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Картинка к процедуре',
                'verbose_name_plural': 'Картинки к процедуре',
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='tags',
            field=models.ManyToManyField(related_name='procedure_tags', to='home.tag', verbose_name='Тэги'),
        ),
        migrations.CreateModel(
            name='OrdersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_procedure', to='home.procedure', verbose_name='Процедура')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('img', models.ImageField(blank=True, upload_to='users/', verbose_name='Аватар')),
                ('birthday', models.DateField(null=True, verbose_name='День рождения')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('user', models.OneToOneField(max_length=150, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='ComplexProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('about', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='complex/', verbose_name='Картинка')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('time', models.PositiveSmallIntegerField(help_text='Время в минутах', verbose_name='Длительность')),
                ('sorting', models.SmallIntegerField(blank=True, verbose_name='Номер сортировки')),
                ('unpublished', models.BooleanField(default=False, verbose_name='Черновик')),
                ('saving', models.PositiveSmallIntegerField(null=True, verbose_name='Экономия')),
                ('procedures', models.ManyToManyField(related_name='complex_procedure', to='home.procedure', verbose_name='Процедуры')),
                ('tags', models.ManyToManyField(related_name='complex_tags', to='home.tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Комплекс',
                'verbose_name_plural': 'Комплексы',
            },
        ),
        migrations.CreateModel(
            name='ComplexImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='complex_shots/', verbose_name='Изображение')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.complexprocedure', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Картинка к комплексу',
                'verbose_name_plural': 'Картинки к комплексу',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('about', models.TextField(verbose_name='Описание')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='Скидка')),
                ('date_start', models.DateField(default=datetime.date.today, verbose_name='Дата начала')),
                ('date_end', models.DateField(default=datetime.date(2022, 6, 11), verbose_name='Дата начала')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('image', models.ImageField(upload_to='actions/', verbose_name='Картинка')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('procedure_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_procedure', to='home.procedure', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
