# Generated by Django 4.0.5 on 2022-06-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_complexprocedure_sorting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='icon',
            field=models.CharField(default=' ', max_length=100, verbose_name='Иконка'),
        ),
    ]
