# Generated by Django 4.0.5 on 2022-06-05 09:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_procedure_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date_end',
            field=models.DateField(default=datetime.date(2022, 6, 12), verbose_name='Дата начала'),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=2500, verbose_name='Сообщение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.questions', verbose_name='Родитель')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.procedure', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
