# Generated by Django 4.0.5 on 2022-06-05 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_action_date_end_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 5)),
        ),
    ]
