# Generated by Django 4.0.5 on 2022-06-05 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 5, 9, 15, 34, 966062, tzinfo=utc)),
        ),
    ]
