# Generated by Django 4.0.5 on 2022-06-07 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_questions_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='date_end',
            field=models.DateField(default=datetime.date(2022, 6, 14), verbose_name='Дата начала'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.ImageField(upload_to='', verbose_name='продолжительность')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customuser', verbose_name='Клиент')),
                ('date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.day', verbose_name='День приема')),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.procedure', verbose_name='Процедура')),
            ],
        ),
    ]
