# Generated by Django 4.0.5 on 2022-06-07 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_day_alter_action_date_end_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата')),
            ],
        ),
        migrations.RemoveField(
            model_name='visit',
            name='date',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='visit',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.day_visit', verbose_name='День приема'),
        ),
    ]
