# Generated by Django 4.0.5 on 2022-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_day_visit_remove_visit_date_delete_day_visit_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='timing',
            field=models.PositiveSmallIntegerField(verbose_name='продолжительность'),
        ),
    ]
