# Generated by Django 4.0.5 on 2022-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_visit_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='timing',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='продолжительность'),
        ),
    ]
