# Generated by Django 4.0.5 on 2022-06-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_visit_timing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
