# Generated by Django 4.0.5 on 2022-06-09 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_visit_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date_end',
            field=models.DateField(default=datetime.date(2022, 6, 16), verbose_name='Дата начала'),
        ),
    ]
